const manifest = {
  "/entertainment/prettymuch-why-dont-we": "/entertainment/prettymuch-why-dont-we-boy-bands",
  "/entertainment/eminem-greatest-rapper-alive": "/entertainment/eminem-the-greatest-rapper-alive-or-overrated",
  "/entertainment/is-keanu-reeves-immortal-2": "/entertainment/keanu-reeves-immortal-matrix-john-wick",
  "/culture/which-cheese-is-better-cheddar-or-gouda": "/culture/cheddar-gouda-best-cheese",
  "/culture/is-five-guys-better-than-shake-shack": "/culture/five-guys-shake-shack-best-burger",
  "/culture/do-white-people-need-to-stop-using-woke": "/culture/do-white-people-need-to-stop",
  "/culture/are-dress-codes-sexist": "/culture/dress-codes-sexist",
  "/culture/is-going-vegan-actually-healthier-than-eating-meat": "/culture/vegan-better-than-meat",
  "/politics/jimmy-carter-good-president": "/politics/jimmy-carter-legacy",
  "/politics/who-better-president-donald-trump-mike-pence": "/politics/mike-pence-better-president-donald-trump",
  "/entertainment/is-drake-the-greatest-rapper-of-all-time": "/entertainment/goat-drake",
  "/politics/stormy-daniels-donald-trump-affair-matters": "/politics/stormy-daniels-donald-trump-michael-cohen",
  "/sports/nfl-ray-lewis-pro-football-hall-of-fame": "/sports/nfl-pro-football-hall-of-fame-ray-lewis-murder-case",
  "/entertainment/who-s-the-better-batman-ben-affleck-or-christian-bale": "/entertainment/ben-affleck-christian-bale-batman",
  "/entertainment/michael-jackson-prince-pop-legends": "/entertainment/michael-jackson-prince-pop-music",
  "/entertainment/jimmy-kimmel-jimmy-fallon": "/entertainment/jimmy-fallon-jimmy-kimmel-king-of-late-night",
  "/sports/who-would-win-in-a-fight-bruce-lee-or-muhammad-ali": "/sports/bruce-lee-muhammad-ali-fight-brawl",
  "/politics/nbc-cancel-megyn-kelly": "/politics/nbc-cancel-megyn-kelly-drama",
  "/entertainment/harry-potter-and-the-cursed-child-running-time": "/entertainment/harry-potter-and-the-cursed-child-broadway-running-time",
  "/entertainment/best-female-prison-show-wentworth-or-orange-is-the-new-black": "/entertainment/wentworth-orange-is-the-new-black",
  "/sports/nba-sneakers-air-jordans-air-force-ones": "/sports/nba-basketball-sneakers-air-jordans-air-force-ones",
  "/entertainment/skyscraper-die-hard": "/entertainment/skyscraper-die-hard-action-movie",
  "/entertainment/which-show-is-better-empire-or-power-2": "/entertainment/empire-power",
  "/sports/what-is-america-s-favorite-pastime-football-or-baseball": "/sports/football-baseball-mlb-nfl-national-pastime",
  "/entertainment/tupac-vs-biggie-who-s-the-greatest-rapper-of-all-time": "/entertainment/tupac-biggie-greatest-rapper-of-all-time-goat",
  "/entertainment/john-lennon-paul-mccartney-the-beatles": "/entertainment/john-lennon-paul-mccartney",
  "/politics/should-a-sitting-president-hold-campaign-rallies-after-the-election": "/politics/donald-trump-campaign-rallies-post-election",
  "/culture/okcupid-vs-tinder-which-online-dating-app-is-better": "/culture/ok-cupid-tinder",
  "/entertainment/which-classic-diva-has-the-best-voice-mariah-carey-or-whitney-houston": "/entertainment/whitney-houston-mariah-carey-goat",
  "/sports/will-rafael-nadal-surpass-roger-federer-as-the-greatest-tennis-player-of-all-time": "/sports/rafael-nadal-roger-federer-tennis",
  "/sports/los-angeles-lakers-nba-lonzo-ball-kyle-kuzma": "/sports/nba-lakers-lonzo-ball-kyle-kuzma",
  "/sports/are-the-golden-state-warriors-ruining-the-nba": "/sports/nba-super-teams-warriors",
  "/politics/net-neutrality-ending-good-internet": "/politics/net-neutrality-end-good-for-internet",
  "/politics/nafta-bad-trade-deal": "/politics/nafta-bad-trade-deal-trump-bernie-sanders",
  "/sports/is-the-nba-rigged-2": "/sports/nba-rigged",
  "/sports/colin-kaepernick-tim-tebow-kneeling-anthem": "/sports/nfl-kneeling-protest-colin-kaepernick-tim-tebow",
  "/politics/ms13-trump-gang-threat": "/politics/ms-13-white-supremacists-america-trump",
  "/politics/unemployment-down-obama-trump": "/politics/unemployment-down-obama-trump-responsible",
  "/sports/greatest-nba-player-of-all-time-lebron-james-or-michael-jordan": "/sports/nba-lebron-james-michael-jordan-goat-greatest",
  "/entertainment/who-would-win-in-a-brawl-wolverine-or-deadpool": "/entertainment/wolverine-deadpool-brawl",
  "/entertainment/backstreet-boys-nsync-bsb": "/entertainment/backstreet-boys-nsync-boy-bands-of-90s",
  "/sports/nfl-sam-darnold-josh-rosen-usc-trojans-ucla-bruins": "/sports/nfl-draft-sam-darnold-josh-rosen-usc-ucla",
  "/politics/should-the-u-s-implement-stricter-gun-control": "/politics/stricter-gun-control-united-states",
  "/entertainment/cardi-b-nicki-minaj-best-female-rapper": "/entertainment/cardi-b-nicki-minaj-best-woman-rapper",
  "/culture/confederate-flag-racism-southern-heritage-hate": "/culture/confederate-flag-racism-charlottesville-white-supremacists",
  "/sports/mike-tyson-vs-muhammad-ali-who-wins-the-ultimate-heavyweight-fight": "/sports/boxing-muhammad-ali-tyson-fight",
  "/sports/nba-liangelo-lamelo-lavar-ball": "/sports/nba-draft-liangelo-ball-lamelo",
  "/sports/ncaa-pay-student-college-athletes": "/sports/ncaa-pay-student-college-athletes-football-basketball",
  "/sports/do-professional-athletes-make-too-much-money": "/sports/nba-nfl-nhl-mlb-overpaid",
  "/politics/chicago-proof-gun-laws-dont-work": "/politics/chicago-proof-gun-laws-fail",
  "/sports/are-professional-athletes-overpaid-2": "/sports/nba-nfl-nhl-mlb-overpaid",
  "/sports/should-kids-be-allowed-to-play-football": "/sports/nfl-youth-football-kids-ban",
  "/culture/who-is-responsible-for-bringing-unemployment-down": "/politics/unemployment-down-obama-trump",
  "/entertainment/cardi-b-nicki-minaj": "/entertainment/cardi-b-nicki-minaj-best-female-rapper",
  "/culture/is-it-racist-to-fly-the-confederate-flag": "/culture/confederate-flag-racism-southern-heritage-hate",
  "/culture/is-the-iphone-x-worth-the-price-tag": "/culture/apple-iphone-x-worth-price-tag-expensive",
  "/culture/would-ending-net-neutrality-actually-be-good-for-the-internet": "/politics/net-neutrality-ending-good-internet",
  "/entertainment/best-k-pop-group-bts-or-exo": "/entertainment/bts-exo-k-pop-group",
  "/entertainment/empire-vs-power-which-show-is-better": "/entertainment/which-show-is-better-empire-or-power-2",
  "/entertainment/in-an-all-out-brawl-who-would-win-justice-league-vs-avengers": "/entertainment/who-would-win-in-an-all-out-brawl-justice-league-or-avengers",
  "/entertainment/is-bill-skarsgard-a-scarier-pennywise-than-tim-curry": "/entertainment/is-bill-skarsgard-a-scarier-pennywise-than-tim-curry-2",
  "/entertainment/which-show-is-better-empire-or-power": "/entertainment/which-show-is-better-empire-or-power-2",
  "/entertainment/who-s-the-better-girl-group-of-2016-little-mix-or-fifth-harmony": "/entertainment/best-girl-group-of-2017-so-far-little-mix-or-fifth-harmony",
  "/entertainment/who-s-the-strongest-marvel-superhero-hulk-or-thor": "/entertainment/hulk-thor-ragnarok-marvel",
  "/politics/chicago-gun-laws": "/politics/chicago-proof-gun-laws-dont-work",
  "/politics/is-chicago-proof-that-gun-laws-don-t-work": "/politics/chicago-gun-laws",
  "/politics/should-english-be-the-official-language-of-the-u-s": "/politics/should-english-be-official-language-usa",
  "/sports/are-professional-athletes-overpaid": "/sports/are-professional-athletes-overpaid-2",
  "/sports/is-nba-2k18-worth-buying": "/sports/nba-2k18-should-you-buy",
  "/sports/is-pro-wrestling-a-fake-sport": "/sports/is-pro-wrestling-a-fake-sport-2",
  "/sports/should-college-athletes-be-paid": "/sports/ncaa-pay-student-college-athletes",
  "/sports/should-college-athletes-be-paid-2": "/sports/ncaa-pay-student-college-athletes",
  "/sports/should-college-athletes-be-paid-3": "/sports/ncaa-pay-student-college-athletes",
  "/sports/who-will-win-in-a-boxing-match-floyd-mayweather-or-conor-mcgregor": "/sports/who-would-win-a-boxing-match-floyd-mayweather-or-conor-mcgregor-2",
  "/sports/who-would-win-a-boxing-match-conor-mcgregor-or-floyd-mayweather": "/sports/who-would-win-a-boxing-match-floyd-mayweather-or-conor-mcgregor-2"
};

export function isOnRedirectManifest(path) {
  return !!manifest[path];
}

export function redirectPath(path) {
  return manifest[path];
}
